<?php
/** Server-rendered boundary map for the Core AI kiosk. @package CoreAiMap */
if ( ! defined( 'ABSPATH' ) ) { exit; }

$timeout = max( 20, min( 180, absint( $attributes['inactivityTimeout'] ?? 60 ) ) );
$offline = ! empty( $attributes['offlineEnabled'] );
$projects = array(
	'plugin' => array( 'AI Plugin', 'Experimental plugin', 'Turn the foundations into useful features', 'Where user-facing AI features are assembled and tested in WordPress.', 'The reference plugin turns the shared Core AI foundations into practical experiences that contributors can inspect, test, and extend.', 'wordpress.org/plugins/ai', 'https://wordpress.org/plugins/ai/' ),
	'client' => array( 'AI Client', 'Core API · 7.0', 'Request AI through one common interface', 'A standard, provider-independent way for WordPress code to request generative AI output.', 'The AI Client gives plugins one common API while connectors handle service discovery, credentials, and connection state.', 'developer.wordpress.org/reference/functions/wp_ai_client_prompt', 'https://developer.wordpress.org/reference/functions/wp_ai_client_prompt/' ),
	'connectors' => array( 'Connectors', 'Core API · 7.0', 'Connect WordPress to providers and services', 'Where a site owner connects WordPress to outside services. Connectors handles discovery, credentials, connection status, and approvals — so the site decides what AI it can reach.', 'Introduced in WordPress 7.0 as a standardized framework for registering and managing connections to external services, starting with AI providers.', 'make.wordpress.org/core → Connectors API in 7.0', 'https://make.wordpress.org/core/' ),
	'mcp' => array( 'MCP Adapter', 'Open adapter', 'Let authorized assistants work with WordPress', 'A bridge that lets authorized assistants discover and call eligible WordPress abilities.', 'The adapter translates Model Context Protocol requests into Abilities API calls. WordPress still owns authentication, permissions, and execution.', 'github.com/WordPress/mcp-adapter', 'https://github.com/WordPress/mcp-adapter' ),
	'abilities' => array( 'Abilities API', 'Core API · 6.9', 'Describe what WordPress can do', 'A shared way to register and discover WordPress capabilities in a human- and machine-readable format.', 'Abilities define inputs, outputs, permissions, and callbacks so plugins, people, and agents can safely discover and invoke site functionality.', 'developer.wordpress.org/apis/abilities-api', 'https://developer.wordpress.org/apis/abilities-api/' ),
	'bench' => array( 'WP Bench', 'Early benchmark', 'Test how well agents perform WordPress work', 'A benchmark for evaluating how well AI agents complete real WordPress development tasks.', 'WP Bench runs generated solutions in sandboxed WordPress environments and grades them with static analysis and runtime assertions.', 'github.com/WordPress/wp-bench', 'https://github.com/WordPress/wp-bench' ),
	'skills' => array( 'Agent Skills', 'Contributor guidance', 'Instruction bundles', 'Reusable, current WordPress guidance that coding assistants can load before they begin work.', 'Skills package focused instructions for blocks, themes, plugins, APIs, performance, and security so agents follow current WordPress conventions.', 'github.com/WordPress/agent-skills', 'https://github.com/WordPress/agent-skills' ),
);
$icons = array(
	'plugin' => '<rect x="4" y="6" width="24" height="20" rx="2"/><path d="M9 13h9m-9 5h14"/>',
	'client' => '<path d="M5 6h22v15H15l-6 5v-5H5V6Z"/><path d="M10 12h12m-12 4h8"/>',
	'connectors' => '<path d="M13 4h6v7h5v6h-5v4a7 7 0 0 1-14 0v-4h8V4Z"/><path d="M8 17v-5m10-1V6"/>',
	'mcp' => '<path d="M11 5v7m10-7v7M8 12h16v3a8 8 0 0 1-8 8v4"/><path d="M12 17h8"/>',
	'abilities' => '<rect x="4" y="5" width="10" height="9" rx="1.5"/><rect x="18" y="18" width="10" height="9" rx="1.5"/><path d="M14 9.5h5a4 4 0 0 1 4 4V18M18 22.5h-5a4 4 0 0 1-4-4V14"/>',
	'bench' => '<path d="M5 27V14m7 13V8m7 19V17m7 10V4"/><path d="M3 27h26"/>',
	'skills' => '<path d="m16 3 2.2 6.1L24 12l-5.8 2.9L16 21l-2.2-6.1L8 12l5.8-2.9L16 3Z"/><path d="m7 20 1.1 3.1L11 24.5l-2.9 1.4L7 29l-1.1-3.1L3 24.5l2.9-1.4L7 20Z"/>',
);
$stories = array(
	'uses-ai' => array( 'WordPress uses AI', 'A plugin asks for a capability. The AI Client routes the request, and Connectors decides which provider the site is allowed to reach.', array( 'plugin', 'client', 'connectors' ) ),
	'uses-wp' => array( 'AI uses WordPress', 'An authorized assistant calls in through the MCP Adapter, which translates the call into a WordPress ability. Permission still belongs to WordPress.', array( 'mcp', 'abilities' ) ),
	'learns' => array( 'An agent learns WordPress', 'Agent Skills attaches current WordPress guidance to a coding assistant before it starts work. This happens outside the site — nothing executes here.', array() ),
	'tests' => array( 'WordPress tests the result', 'WP Bench runs what the agent produced inside a sandboxed WordPress and grades it. Evidence about the work, not a leaderboard.', array( 'bench' ) ),
);
$context = array( 'screen' => 'attract', 'selectedProject' => '', 'activeScenario' => 'uses-ai', 'scenarioPaths' => array(), 'announcement' => __( 'Core AI boundary map ready.', 'core-ai-map' ), 'toast' => '', 'isOffline' => false, 'idleScenarioIndex' => 0 );
$context['scenarioPaths'] = array(); foreach ( $stories as $id => $story ) { $context['scenarioPaths'][ $id ] = $story[2]; }
$wrapper = get_block_wrapper_attributes( array( 'class' => 'core-ai-map', 'data-wp-interactive' => 'core-ai/map', 'data-wp-run' => 'callbacks.useKiosk', 'data-wp-class--is-attract' => 'state.isAttract', 'data-wp-class--is-map' => 'state.isMap', 'data-wp-class--is-detail' => 'state.isDetail', 'data-wp-class--story-uses-ai' => 'state.isUsesAi', 'data-wp-class--story-uses-wp' => 'state.isUsesWp', 'data-wp-class--story-learns' => 'state.isLearns', 'data-wp-class--story-tests' => 'state.isTests', 'data-inactivity-timeout' => (string) ( $timeout * 1000 ), 'data-offline-enabled' => $offline ? 'true' : 'false' ) );
?>
<section <?php echo $wrapper; // phpcs:ignore ?> <?php echo wp_interactivity_data_wp_context( $context ); // phpcs:ignore ?>>
	<div class="core-ai-map__grid" aria-hidden="true"></div>
	<header class="core-ai-map__topbar">
		<div class="core-ai-map__brand"><img src="<?php echo esc_url( CORE_AI_MAP_URL . 'assets/icon.svg' ); ?>" alt="" width="30" height="30"><span>WordPress Core AI</span></div>
		<div class="core-ai-map__promptbar" data-wp-bind--hidden="state.isAttract"><span aria-hidden="true">⊞</span> Explore how WordPress’s AI building blocks connect</div>
		<div class="core-ai-map__offline" data-wp-bind--hidden="state.isOnline"><i></i> Offline mode</div>
		<button class="core-ai-map__reset" type="button" data-wp-bind--hidden="state.isAttract" data-wp-on--click="actions.reset">Start over</button>
	</header>
	<div class="core-ai-map__stage">
		<div class="core-ai-map__plate"></div>
		<p class="core-ai-map__edge-label assistants">Outside · assistants</p><p class="core-ai-map__edge-label inside">Inside WordPress</p><p class="core-ai-map__edge-label providers">Outside · AI providers</p><p class="core-ai-map__edge-label evaluation" data-wp-bind--hidden="state.isAttract">Below the runtime · evaluation</p>
		<svg class="core-ai-map__paths" viewBox="0 0 1366 1024" aria-hidden="true"><defs><marker id="cai-tip" viewBox="0 0 10 10" refX="8.5" refY="5" markerWidth="4.6" markerHeight="4.6" orient="auto"><path d="M0 0L10 5L0 10z"/></marker></defs>
			<g class="rules"><path class="left" d="M240 112V600"/><path class="right" d="M1030 112V600"/><path class="runtime" d="M240 628H1030"/></g>
			<g class="rests"><path d="M504 234H556"/><path d="M792 234H912"/><path d="M674 308V400"/><path d="M358 474H556"/></g>
			<g class="story-path uses-ai"><path d="M504 234H556"/><path d="M792 234H912"/><path d="M1090 308C1112 340 1122 364 1146 377"/></g><g class="story-path uses-wp"><path d="M114 276C114 342 162 372 230 395"/><path d="M358 474H556"/></g><g class="story-path learns"><path d="M114 278V296"/><path d="M204 350C224 344 234 338 240 330"/></g><g class="story-path tests"><path d="M114 402C114 630 176 748 336 748H546"/></g>
		</svg>
		<?php
		$actors = array( 'assistant' => array( 'Not WordPress', 'AI assistant', 'Speaks MCP', 'state.hideAssistant', '1' ), 'skills' => array( 'Guidance', 'Agent Skills', 'Instruction bundles', 'state.hideSkills', '1' ), 'agent' => array( 'Not WordPress', 'Coding agent', 'Writes the code', 'state.hideAgent', '2' ), 'provider' => array( 'Not WordPress', 'AI provider', 'The site owner’s choice', 'state.hideProvider', '4' ) );
		foreach ( $actors as $id => $actor ) : $is_skills = 'skills' === $id; ?>
			<div class="core-ai-map__actor core-ai-map__actor--<?php echo esc_attr( $id ); ?>" data-wp-bind--hidden="<?php echo esc_attr( $actor[3] ); ?>"><?php if ( $is_skills ) : ?><i></i><i></i><?php endif; ?>
			<?php if ( $is_skills ) : ?><button type="button" data-wp-on--click="actions.selectProject" <?php echo wp_interactivity_data_wp_context( array( 'projectId' => 'skills' ) ); // phpcs:ignore ?>><?php else : ?><div><?php endif; ?><b class="core-ai-map__step"><?php echo esc_html( $actor[4] ); ?></b><small><?php echo esc_html( $actor[0] ); ?></small><strong><?php echo esc_html( $actor[1] ); ?></strong><span><?php echo esc_html( $actor[2] ); ?></span><?php echo $is_skills ? '</button>' : '</div>'; // phpcs:ignore ?></div>
		<?php endforeach; ?>
		<?php foreach ( array( 'plugin', 'client', 'connectors', 'mcp', 'abilities', 'bench' ) as $id ) : $p = $projects[ $id ]; ?>
		<div class="core-ai-map__node core-ai-map__node--<?php echo esc_attr( $id ); ?>" <?php echo wp_interactivity_data_wp_context( array( 'projectId' => $id ) ); // phpcs:ignore ?> data-wp-class--is-active="state.isProjectActive" data-wp-class--is-dimmed="state.isProjectDimmed"><button type="button" data-wp-on--click="actions.selectProject"><b class="core-ai-map__step"></b><span class="core-ai-map__node-top"><svg viewBox="0 0 32 32" aria-hidden="true"><?php echo $icons[ $id ]; // phpcs:ignore ?></svg><small><?php echo esc_html( $p[1] ); ?></small></span><span><strong><?php echo esc_html( $p[0] ); ?></strong><em><?php echo esc_html( $p[2] ); ?></em></span></button></div>
		<?php endforeach; ?>
	</div>
	<div class="core-ai-map__attract"><p>WordPress Core AI</p><h1><?php echo esc_html( $attributes['title'] ?? 'How do WordPress and AI work together?' ); ?></h1><div class="core-ai-map__deck">See WordPress call AI, let authorized agents call WordPress, and test what they build.</div><button class="core-ai-map__cta core-ai-map__prompt" type="button" data-wp-on--click="actions.start"><span>＋</span> Add the blocks to the canvas</button><div class="core-ai-map__attract-stories"><?php foreach ( $stories as $id => $story ) : ?><p <?php echo wp_interactivity_data_wp_context( array( 'scenarioId' => $id ) ); // phpcs:ignore ?> data-wp-bind--hidden="state.isScenarioNotSelected"><b><?php echo esc_html( $story[0] ); ?></b> <?php echo esc_html( $story[1] ); ?></p><?php endforeach; ?></div></div>
	<div class="core-ai-map__captions"><?php foreach ( $stories as $id => $story ) : ?><p <?php echo wp_interactivity_data_wp_context( array( 'scenarioId' => $id ) ); // phpcs:ignore ?> data-wp-bind--hidden="state.isScenarioNotSelected"><strong><?php echo esc_html( $story[0] ); ?></strong> <?php echo esc_html( $story[1] ); ?></p><?php endforeach; ?></div>
	<nav class="core-ai-map__rail" aria-label="Follow a story"><?php $n = 0; foreach ( $stories as $id => $story ) : ++$n; ?><button type="button" <?php echo wp_interactivity_data_wp_context( array( 'scenarioId' => $id ) ); // phpcs:ignore ?> data-wp-on--click="actions.selectScenario" data-wp-class--is-active="state.isScenarioSelected"><span>0<?php echo esc_html( (string) $n ); ?></span><?php echo esc_html( $story[0] ); ?></button><?php endforeach; ?></nav>
	<?php foreach ( $projects as $id => $p ) : ?><aside class="core-ai-map__details" <?php echo wp_interactivity_data_wp_context( array( 'projectId' => $id ) ); // phpcs:ignore ?> data-wp-bind--hidden="state.isProjectNotSelected"><button class="core-ai-map__details-close" type="button" data-wp-on--click="actions.closeDetails"><span>←</span> Back to the map</button><span class="core-ai-map__chip"><?php echo esc_html( $p[1] ); ?></span><h2><?php echo esc_html( $p[0] ); ?></h2><p class="core-ai-map__lede"><?php echo esc_html( $p[3] ); ?></p><?php if ( 'connectors' === $id ) : ?><h3>Connection states</h3><div class="core-ai-map__states"><span>Available</span><span>Needs plugin</span><span>Needs credentials</span><span>Connected</span></div><h3>Providers</h3><p>Provider plugins register themselves with the AI Client and appear under Settings → Connectors. The map stays vendor-neutral: no provider owns a position on the canvas.</p><?php endif; ?><h3>Under the hood</h3><p><?php echo esc_html( $p[4] ); ?></p><div class="core-ai-map__qr"><img src="<?php echo esc_url( CORE_AI_MAP_URL . 'assets/qr/' . $id . '.svg' ); ?>" alt="QR code for <?php echo esc_attr( $p[0] ); ?> documentation"><div><small>Scan to keep exploring</small><strong><?php echo esc_html( $p[5] ); ?></strong><span>Keep exploring on your own device.</span></div></div></aside><?php endforeach; ?>
	<div class="core-ai-map__home" aria-hidden="true"></div><p class="core-ai-map__announce" aria-live="polite" data-wp-text="state.announcement"></p>
</section>
